### ISSUE TITLE
convert official weights 

### ISSUE THREAD

**Issue by betterze** [moono/stylegan2-tf-2.x#1]
Dear Moono,

Thank you for shaing this great implement. I really apreeciate it. 

If I want to convert the weight from tf1 to tf2, I should download the weights from stylegan2 website (stylegan2-ffhq-config-f.pkl), and place it under official-pretrained folder, is this correct?

Then i run inference_from_official_weights.py. It output:
~~~
DataLossError: Unable to open table file ./official-pretrained/stylegan2-ffhq-config-f.pkl: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
~~~

Could you tell me how to solve this issue?

Thank you again for your help.

Best Wishes,

Alex

**Comment by betterze** [comment]
Problem solved. Just need to load pkl in tf1, then save it as cktp.

code from https://gitmemory.com/issue/moono/stylegan-reproduced/1/486484910

~~~
import os
import pprint
import pickle
import numpy as np
import PIL.Image
import dnnlib
import dnnlib.tflib as tflib
import config

import tensorflow as tf


def main():
    # Initialize TensorFlow.
    tflib.init_tf()

    # Load pre-trained network.
    url = 'https://drive.google.com/uc?id=1MEGjdvVpUsu1jB4zrXZN7Y4kBBOzizDQ' # karras2019stylegan-ffhq-1024x1024.pkl
    with dnnlib.util.open_url(url, cache_dir=config.cache_dir) as f:
        _G, _D, Gs = pickle.load(f)
        # _G = Instantaneous snapshot of the generator. Mainly useful for resuming a previous training run.
        # _D = Instantaneous snapshot of the discriminator. Mainly useful for resuming a previous training run.
        # Gs = Long-term average of the generator. Yields higher-quality results than the instantaneous snapshot.

    # Print network details.
    Gs.print_layers()

    # t_var = tf.trainable_variables()
    # pprint.pprint(t_var)

    saver = tf.train.Saver()

    save_path = saver.save(tf.get_default_session(), "./model.ckpt")


if __name__ == "__main__":
    main()
~~~

**Comment by starrabb1t** [comment]
But module `dnnlib` uses tensorflow v1. I tried to replace `tensorflow` to `tensorflow.compat.v1` in `dnnlib`, but it doesn't work unfortunately.

**Comment by betterze** [comment]
@starrabb1t I mean save the weight in tf1, then you can use tf2 to open this model and load weights.

**Comment by Akila-Ayanthi** [comment]
@betterze I saved the weights in tf1 and used tf2 to open the model and load weights. I used https://drive.google.com/uc?id=1BUL-RIzXC7Bpnz2cn230CbA4eT7_Etp0 as the 256 pretrained model.
I keep getting this error.
![image](https://user-images.githubusercontent.com/40143820/127307244-a3ea221c-91a5-4a1e-99d7-20eee959ff0a.png)

Can you please help me?
Or is there another 256 FFHQ model that I can use?

**Comment by Akila-Ayanthi** [comment]
> But module `dnnlib` uses tensorflow v1. I tried to replace `tensorflow` to `tensorflow.compat.v1` in `dnnlib`, but it doesn't work unfortunately.
> 
> I converted it using this [colab](https://colab.research.google.com/drive/15EGSIv_jZxDvYWODNwEG-I4pV9i3RwlN?usp=sharing) notebook finally. May be useful for those who don't want to have a deal with docker :)

Hi, where exactly is the conversion happening in this colab[https://colab.research.google.com/drive/15EGSIv_jZxDvYWODNwEG-I4pV9i3RwlN?usp=sharing](url) u stated? It's not clear to me.
