### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by Akila-Ayanthi** [moono/stylegan2-tf-2.x#11]
Hi, 
This is exactly what I was looking for. Thank you.
But, it is not clear to me how the training needs to be done. Could you please help me with that?

**Comment by moono** [comment]
I used followings to train on FFHQ dataset,
* Refer to [FFHQ dataset repo](https://github.com/NVlabs/ffhq-dataset) to create `*.tfrecord` for resolution of your interest.
* Please use `docker` for training envrionment.
  * Recommended docker image : `nvcr.io/nvidia/tensorflow:21.03-tf2-py3`
* Train with `train.py`
  * example 256x256 resolution
```bash
# adjust shuffle_buffer_size and batch_size_per_replica to fit your hardware
~$ python train.py \
--allow_memory_growth false \
--use_tf_function true \ 
--use_custom_cuda true \
--model_base_dir <directory-of-output-trained-model> \
--tfrecord_dir <FFHQ-tfrecord-dir> \
--train_res 256 \
--shuffle_buffer_size 5000 \
--batch_size_per_replica 16
```

**Comment by Akila-Ayanthi** [comment]
Thank you.
