### ISSUE TITLE
Training on custom dataset failed

### ISSUE THREAD

**Issue by mbrelab** [moono/stylegan2-tf-2.x#5]
Hello, I was trying to run the code with the following command:

`python train.py --tfrecord_dir=../datasets/butterfly-dataset --train_res=1024`

and get the following error message:

> 2020-09-30 19:31:44.655206: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at conv_grad_input_ops.cc:1103 : Resource exhausted: OOM when allocating tensor with shape[4,64,511,511] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "train.py", line 438, in <module>
    main()
  File "train.py", line 433, in main
    trainer.train(dist_dataset, strategy)
  File "train.py", line 261, in train
    d_loss = dist_d_train_step((real_images, ))
  File "/media/chembiodep/Storage/GREAT/penv38/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/media/chembiodep/Storage/GREAT/penv38/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/media/chembiodep/Storage/GREAT/penv38/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/media/chembiodep/Storage/GREAT/penv38/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "/media/chembiodep/Storage/GREAT/penv38/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/media/chembiodep/Storage/GREAT/penv38/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 545, in call
    outputs = execute.execute(
  File "/media/chembiodep/Storage/GREAT/penv38/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InternalError: 3 root error(s) found.
  (0) Internal:  cudaErrorNoKernelImageForDevice
	 [[node replica_1/discriminator/1024x1024/skip/UpFirDn2D (defined at <string>:98) ]]
	 [[mul/_222]]
  (1) Internal:  cudaErrorNoKernelImageForDevice
	 [[node replica_1/discriminator/1024x1024/skip/UpFirDn2D (defined at <string>:98) ]]
  (2) Internal:  cudaErrorNoKernelImageForDevice
	 [[node replica_1/discriminator/1024x1024/skip/UpFirDn2D (defined at <string>:98) ]]
	 [[AddN_94/_234]]
0 successful operations.
0 derived errors ignored. [Op:__inference_dist_d_train_step_61417]

>Errors may have originated from an input operation.
Input Source operations connected to node replica_1/discriminator/1024x1024/skip/UpFirDn2D:
 replica_1/discriminator/1024x1024/skip/Reshape (defined at /media/chembiodep/Storage/GREAT/butterfly/stylegan2-tf-2.x/stylegan2/layers/cuda/upfirdn_2d_v2.py:105)	
 replica_1/discriminator/1024x1024/skip/Const (defined at /media/chembiodep/Storage/GREAT/butterfly/stylegan2-tf-2.x/stylegan2/layers/cuda/upfirdn_2d_v2.py:129)

>Input Source operations connected to node replica_1/discriminator/1024x1024/skip/UpFirDn2D:
 replica_1/discriminator/1024x1024/skip/Reshape (defined at /media/chembiodep/Storage/GREAT/butterfly/stylegan2-tf-2.x/stylegan2/layers/cuda/upfirdn_2d_v2.py:105)	
 replica_1/discriminator/1024x1024/skip/Const (defined at /media/chembiodep/Storage/GREAT/butterfly/stylegan2-tf-2.x/stylegan2/layers/cuda/upfirdn_2d_v2.py:129)

>Input Source operations connected to node replica_1/discriminator/1024x1024/skip/UpFirDn2D:
 replica_1/discriminator/1024x1024/skip/Reshape (defined at /media/chembiodep/Storage/GREAT/butterfly/stylegan2-tf-2.x/stylegan2/layers/cuda/upfirdn_2d_v2.py:105)	
 replica_1/discriminator/1024x1024/skip/Const (defined at /media/chembiodep/Storage/GREAT/butterfly/stylegan2-tf-2.x/stylegan2/layers/cuda/upfirdn_2d_v2.py:129)

>Function call stack:
dist_d_train_step -> dist_d_train_step -> dist_d_train_step

Here is the file structure:

>butterfly/
├── datasets/
│   └── butterfly-dataset
│   │   └── ...
└── stylegan2-tf-2.x
    ├── train.py
    └── ...

Spec:
Quadro P6000
TITAN V
CUDA version: 11.1

**Comment by moono** [comment]
Assuming that you have correctly modified code to load your dataset,
it looks like you don't have enough gpu memory to run 1024x1024. 

You could ...
decrease batch size
change the gpu (I would recommend V100 32GB)
lower your dataset image size

**Comment by mbrelab** [comment]
I tried to reduce the resolution to 256x256 but it stop responding at

> Loading... Done.
Not restoring from saved checkpoint
Start Training
max_steps: 3125000
WARNING:tensorflow:From /media/chembiodep/Storage/GREAT/penv38/lib/python3.8/site-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py:601: get_next_as_optional (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Iterator.get_next_as_optional()` instead.

**Comment by moono** [comment]
That's normal. At first training step, it will take few minutes.

**Comment by mbrelab** [comment]
Thank you for your response!

**Comment by mbrelab** [comment]
I have ran it on for 18 hours but yet to see the report of first step. I checked events file with tensorboard but no events were written. How should I set up to see if the experiment is running or not?

**Comment by moono** [comment]
I think you should first check your tensorflow environment is using GPU or not.
You said that you're using `CUDA version: 11.1`, no tensorflow 2.x versions have pre-compiled binaries for CUDA 11 as far as I know, unless you compiled it yourself.

If I remember correctly, tf2.0 uses CUDA 10.0, and later ones uses CUDA 10.1.
I've checked this repository's code in tf 2.0 and tf 2.3 and working correctly.

check: [tensorflow installation with GPU](https://www.tensorflow.org/install/gpu)

Also run the code in docker container if possible.

After that you have checked the GPU setup, I recommend that you test your dataset loader.

**Comment by mbrelab** [comment]
I have checked and tensorflow does recognize the GPU as here is the log of one of the run

> 2020-10-02 11:16:31.344292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1
2020-10-02 11:16:31.344326: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-02 11:16:31.344350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1 
2020-10-02 11:16:31.344354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N N 
2020-10-02 11:16:31.344370: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   N N 
2020-10-02 11:16:31.346257: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/device:GPU:0 with 10543 MB memory) -> physical GPU (device: 0, name: TITAN V, pci bus id: 0000:41:00.0, compute capability: 7.0)
2020-10-02 11:16:31.347200: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/device:GPU:1 with 22728 MB memory) -> physical GPU (device: 1, name: Quadro P6000, pci bus id: 0000:0a:00.0, compute capability: 6.1)

for the dataset, I have used the script from the original StyleGAN to create the .tfrecords

`python dataset_tool.py create_from_images ~/datasets/my-custom-dataset ~/my-custom-images`

**Comment by moono** [comment]
I see.
First of all, the code is meant to use all the GPUs available within current environment using [mirrored strategy](https://www.tensorflow.org/guide/distributed_training).

The only difference between your environment and mine is that you are using two different GPU types.
(I don't have any experience in these kind of setup.)
I have always used same GPUs for muti-gpu training (V100 32GB) or just single GPU.
But you are mixing V100 11GB(?) and P6000 (24GB).
According to your log your GPUs are not interconnected each other? [explanation](https://stackoverflow.com/questions/52192461/what-is-device-interconnect-streamexecutor-with-strength-1-edge-matrix) which I think it is slowing down your training.

You could use just one GPU to tryout that your code is working or not.
And please use docker.

**Comment by mbrelab** [comment]
I was able to run training with a single GPU!
