### ISSUE TITLE
What are the "labels" in the generator and discriminator?

### ISSUE THREAD

**Issue by NoAchache** [moono/stylegan2-tf-2.x#7]
Thank you for this awesome repo! I just really struggle to understand what are supposed to be the labels in the generator and discriminator, although they are not actually used since labels_dim is 0 by default for training? (c.f. labels in `g_logistic_ns_pathreg`)

**Comment by moono** [comment]
"labels" is used for conditional gan. It's kind of legacy code from official repo.
As you said, for FFHQ dataset which targets to train and generate various faces you don't need labels so the dimension is 0.

But if you have dataset with labels (here, categorical onehot labels) you can train stylegan2 as conditional which uses label conditioning (see last few lines in call() in discriminator). And this label conditioning works really well.

**Comment by NoAchache** [comment]
Thank you very much for your answer, it makes sense now :+1:
