### ISSUE TITLE
NHWC Support

### ISSUE THREAD

**Issue by sailor002** [moono/stylegan2-tf-2.x#9]
Hi, thanks for the great repo. I am trying to convert the generator model to tflite. I get this error: "Unexpected value for attribute 'data_format'. Expected 'NHWC'." Do you have an option for NHWC? Or do you have any other idea to convert the generator to tflite file? Thanks...

**Comment by moono** [comment]
Hello,
Sorry but this repo only supports NCHW format.
This repo was intended to copy official stylegan2 repo and just wrapped as tf2 compatible.

If you need NHWC format you need to change all layers and train from zero I guess.

**Comment by sailor002** [comment]
Ok, I understand. Thanks for the reply :)
